simplified lf paste

diff --git a/cp-p b/cp-p
--- a/cp-p
+++ b/cp-p
@@ -28,84 +28,85 @@ function human_time(t) {
     return sprintf("%s%s%.1fs", h, m, s)
 }'
 
-if [ "$1" = --mv ]; then
-    cmd='mv'
-    shift
-else
-    cmd='cp
--r'
-fi
-
-if [ "$1" = --new-line ]; then
-    R='\n'
-    B=''
-    W=99999999
-    shift
-else
-    R=''
-    B='\033[0E\033[K'
-    W=$(tput cols)
-fi
-
-# ARGS STUFF
-
-srcs=''
-srcF=''
-dest=''
-opts=''
-
-i=1
-while [ $i -le $# ]; do
-    arg=$(eval echo '$'$i)
-    if [ $i = $# ] && [ ! "$dest" ]; then
-        dest="$arg"
-        break
-    fi
-    if [ -e "$arg" ]; then
-        srcs="$srcs$arg
-"
-    elif [ "$arg" = '-t' ]; then
-        i=$((i + 1))
-        dest=$(eval echo '$'$i)
-    elif [ "$arg" = '-F' ]; then
-        ##### -F: file including sources files #####
-        i=$((i + 1))
-        srcF=$(eval echo '$'$i)
+copy() {
+    if [ "$1" = --mv ]; then
+        cmd='mv'
+        shift
     else
-        opts="$opts$arg
-"
+        cmd='cp
+-r'
     fi
-    i=$((i + 1))
-done
 
-if [ "$srcF" ]; then
-    while read -r line; do
-        if [ -e "$line" ]; then
-            srcs="$srcs$line
+    if [ "$1" = --new-line ]; then
+        R='\n'
+        B=''
+        W=99999999
+        shift
+    else
+        R=''
+        B='\033[0E\033[K'
+        W=$(tput cols)
+    fi
+
+    # ARGS STUFF
+
+    srcs=''
+    srcF=''
+    dest=''
+    opts=''
+
+    i=1
+    while [ $i -le $# ]; do
+        arg=$(eval echo '$'$i)
+        if [ $i = $# ] && [ ! "$dest" ]; then
+            dest="$arg"
+            break
+        fi
+        if [ -e "$arg" ]; then
+            srcs="$srcs$arg
+"
+        elif [ "$arg" = '-t' ]; then
+            i=$((i + 1))
+            dest=$(eval echo '$'$i)
+        elif [ "$arg" = '-F' ]; then
+            ##### -F: file including sources files #####
+            i=$((i + 1))
+            srcF=$(eval echo '$'$i)
+        else
+            opts="$opts$arg
 "
         fi
-    done < "$srcF"
-fi
+        i=$((i + 1))
+    done
 
-# remove last empty line
-srcs=$(echo "$srcs" | head -c -1)
-
-if [ ! "$srcs" ] || [ ! "$dest" ]; then
-    if [ "$cmd" = mv ]; then
-        mv --help
-    else
-        cp --help
+    if [ "$srcF" ]; then
+        while read -r line; do
+            if [ -e "$line" ]; then
+                srcs="$srcs$line
+"
+            fi
+        done < "$srcF"
     fi
-    exit 1
-fi
 
-# THE ACTUAL THING
+    # remove last empty line
+    srcs=$(echo "$srcs" | head -c -1)
 
-printf $B'Calculating size'$R
+    if [ ! "$srcs" ] || [ ! "$dest" ]; then
+        if [ "$cmd" = mv ]; then
+            mv --help
+        else
+            cp --help
+        fi
+        exit 1
+    fi
 
-exists=0
-total_size=0
-IFS='
+    # THE ACTUAL THING
+
+    printf $B'Calculating size'$R
+
+    exists=0
+    total_size=0
+    IFS='
 '; for src in $srcs; do
        exists=1
        arg_size=$(du -sb "$src" 2>/dev/null | awk '{print $1}')
@@ -114,15 +115,15 @@ IFS='
        fi
    done
 
-if [ "$exists" = "0" ]; then
-    echo "ERROR: No source file specified exists. Please try again"
-    exit 1
-fi
+    if [ "$exists" = "0" ]; then
+        echo "ERROR: No source file specified exists. Please try again"
+        exit 1
+    fi
 
-total_size_h=$(echo $total_size | awk "$H_FUN"'{print human($1)}')
+    total_size_h=$(echo $total_size | awk "$H_FUN"'{print human($1)}')
 
-count=0
-IFS='
+    count=0
+    IFS='
 '; for src in $srcs; do
 
        # if same name
@@ -174,8 +175,40 @@ IFS='
        count=$((count + arg_size))
    done
 
-if [ "$cmd" = mv ]; then
-    echo 'Done moving'
-else
-    echo 'Done copying'
-fi
+    if [ "$cmd" = mv ]; then
+        echo 'Done moving'
+    else
+        echo 'Done copying'
+    fi
+
+}
+
+# to be used only for `lf` file manager. cp-p and mv-p must be on $PATH
+lf_paste() {
+    id="$1"
+    send="while read -r line; do lf -remote \"send $id echo \$line\"; done && lf -remote 'send reload'"
+    load=$(lf -remote 'load')
+    mode=$(echo "$load" | sed -n '1p')
+    srcF=$(mktemp)
+    echo "$load" | sed '1d' > "$srcF"
+    s='' && [ ! -w . ] && s='sudo'
+    case "$mode" in
+        copy) cmd='cp-p';; move) cmd='mv-p';;
+    esac
+    cmd="$cmd --new-line"
+    [ "$mode" = copy ] && cmd="$cmd -a"
+    sh -c "$s $cmd --backup=numbered -F \"$srcF\" . | $send && rm -f \"$srcF\" &"
+    lf -remote 'send load'
+    lf -remote 'send clear'
+}
+
+main() {
+    if [ "$1" = '--lf-paste' ]; then
+        shift
+        lf_paste "$@"
+    else
+        copy "$@"
+    fi
+}
+
+main "$@"
