Add new features and improvements

diff --git a/cp-p b/cp-p
--- a/cp-p
+++ b/cp-p
@@ -33,16 +33,22 @@ help() {
     echo "Usage: ${orig}-p [OPTION]... SOURCE DEST"
     echo "Like ${orig} but with progress information."
     echo
-    echo "  -F FILE    read source paths from FILE"
-    echo "  --new-line show every progress step in a new line"
-    echo "  --lf-paste to be used for lf file manager."
-    echo "             Add 'cmd paste \$cp-p --lf-paste \$id' to"
-    echo "             ~/.config/lf/lfrc"
-    echo "  --help     display this help and exit"
+    echo "  -F FILE     read source paths from FILE"
+    echo "  --new-line  show every progress step in a new line"
+    echo "  --no-timing suppress timing information"
+    echo "  --lf-paste  to be used for lf file manager."
+    echo "              Add 'cmd paste \$cp-p --lf-paste \$id' to"
+    echo "              ~/.config/lf/lfrc"
+    echo "  --help      display this help and exit"
     echo
     echo "Check ${orig} --help for more options."
 
     exit 1
+}
+
+err() {
+    printf '%s-p: %s\n' "$(echo "$cmd" | head -n1)" "$2" 1>&2
+    [ "$1" -gt 0 ] && exit $1
 }
 
 main() {
@@ -52,73 +58,84 @@ main() {
         return
     fi
 
-    if [ "$1" = --mv ]; then
-        cmd='mv'
+    # ARGS STUFF
+
+    mv_opt=0
+    new_line_opt=0
+    no_timing_opt=0
+    help_opt=0
+    end_of_opts=0
+
+    srcs=''
+    srcF=''
+    dest=''
+    last=''
+    opts=''
+
+    while [ $# -gt 0 ]; do
+        arg=$1
         shift
+        if [ $end_of_opts -eq 0 ]; then
+            case "$arg" in
+                -F) if [ $# -gt 0 ]; then
+                        srcF=$1; shift; continue
+                    else
+                        err 1 "'F' option requires an argument"
+                    fi ;;
+                -t) if [ $# -gt 0 ]; then
+                        dest=$1; shift; continue
+                    else
+                        err 1 "'t' option requires an argument"
+                    fi ;;
+                --mv) mv_opt=1; continue ;;
+                --new-line) new_line_opt=1; continue ;;
+                --no-timing) no_timing_opt=1; continue ;;
+                --help) help_opt=1; continue ;;
+                --) end_of_opts=1; continue ;;
+                -*) opts=$(printf '%s\n%s' "$opts" "$arg"); continue ;;
+            esac
+        fi
+        srcs=$(printf '%s\n%s' "$srcs" "$last")
+        last=$arg
+    done
+
+    if [ -z "$dest" ]; then
+        dest=$last
+    else
+        srcs=$(printf '%s\n%s' "$srcs" "$last")
+    fi
+
+    if [ "$srcF" ]; then
+        if [ ! -f "$srcF" ]; then
+            err 1 "failed to access '"$srcF"': No such file"
+        fi
+        while read -r line; do
+            srcs=$(printf '%s\n%s' "$srcs" "$line")
+        done < "$srcF"
+    fi
+
+    srcs=${srcs#?}  # remove first empty line
+    opts=${opts#?}  #
+
+    if [ $mv_opt -eq 1 ]; then
+        cmd='mv'
     else
         cmd='cp
 -r'
     fi
 
-    if [ "$1" = --help ]; then
-        help
-    fi
-
-    if [ "$1" = --new-line ]; then
+    if [ $new_line_opt -eq 1 ]; then
         R='\n'
         B=''
         W=99999999
-        shift
     else
         R=''
-        B='\033[0E\033[K'
+        #B='\033[0E\033[K'
+        B='\r\033[K'
         W=$(tput cols)
     fi
 
-    # ARGS STUFF
-
-    srcs=''
-    srcF=''
-    dest=''
-    opts=''
-
-    i=1
-    while [ $i -le $# ]; do
-        arg=$(eval echo '$'$i)
-        if [ $i = $# ] && [ ! "$dest" ]; then
-            dest="$arg"
-            break
-        fi
-        if [ -e "$arg" ]; then
-            srcs="$srcs$arg
-"
-        elif [ "$arg" = '-t' ]; then
-            i=$((i + 1))
-            dest=$(eval echo '$'$i)
-        elif [ "$arg" = '-F' ]; then
-            ##### -F: file including sources files #####
-            i=$((i + 1))
-            srcF=$(eval echo '$'$i)
-        else
-            opts="$opts$arg
-"
-        fi
-        i=$((i + 1))
-    done
-
-    if [ "$srcF" ]; then
-        while read -r line; do
-            if [ -e "$line" ]; then
-                srcs="$srcs$line
-"
-            fi
-        done < "$srcF"
-    fi
-
-    # remove last empty line
-    srcs=$(echo "$srcs" | head -c -1)
-
-    if [ ! "$srcs" ] || [ ! "$dest" ]; then
+    if [ $help_opt -eq 1 ] || [ ! "$srcs" ] || [ ! "$dest" ]; then
         help
     fi
 
@@ -126,24 +143,44 @@ main() {
 
     printf $B'Calculating size...'$R
 
-    exists=0
+    realdest=$(realpath -- "$dest")
+
     total_size=0
+    srcs_count=0
+    sizes=''
+    srcsE=''
     IFS='
 '; for src in $srcs; do
-       exists=1
-       arg_size=$(du -sb "$src" 2>/dev/null | awk '{print $1}')
-       if [ -n "$arg_size" ]; then
-           total_size=$((total_size + arg_size))
-       fi
-   done
+        [ -e "$src" ] || continue
+        arg_size=$(du -sb -- "$src" 2>/dev/null | awk '{print $1}')
+        [ -n "$arg_size" ] || arg_size=0
+        total_size=$((total_size + arg_size))
+        sizes=$(printf '%s\n%s' "$sizes" "$arg_size")
+        srcsE=$(printf '%s\n%s' "$srcsE" "$src")
+        srcs_count=$(($srcs_count+1))
+    done
+    sizes=${sizes#?}  # remove first empty line
+    srcs=${srcsE#?}   #
+    unset srcsE
 
-    if [ "$exists" = "0" ]; then
-        echo "ERROR: No source file specified exists. Please try again"
-        exit 1
+    printf $B''
+
+    if [ "$srcs_count" -eq 0 ]; then
+        err 1 "no source file specified exists. Please try again"
+    fi
+
+    if [ "$srcs_count" -gt 1 ] && [ ! -d "$realdest" ]; then
+        err 1 "target '"$dest"' is not a directory"
+    fi
+
+    if [ "$srcs_count" -eq 1 ] && [ -f "$realdest" ] && [ -d "$srcs" ] && [ ! -L "$srcs" ] ; then
+        err 1 "cannot overwrite non-directory '"$dest"' with directory '"$srcs"'"
     fi
 
     total_size_h=$(echo $total_size | awk "$H_FUN"'{print human($1)}')
 
+    set -- $sizes
+    unset sizes
 
     if [ "$cmd" = mv ]; then
         printf $B'Moving...'$R
@@ -156,16 +193,17 @@ main() {
 '; for src in $srcs; do
 
        # if same name
-       fname=$(basename "$src")
-       finaldest=$(realpath "$dest")
-       if [ -e "$dest/$fname" ]; then
+       fname=${src%"${src##*[!/]}"}
+       fname=${fname##*/} && [ -z "$fname" ] && fname='/'
+       finaldest=$realdest
+       if [ -e "$finaldest/$fname" ]; then
+           body=${fname%.*}
+           body=${body%.tar}
+           ext=${fname#$body}
            copy_n=
            # keep looping till a new name is found
            while :; do
-               finaldest="$dest/$fname"
-               finaldest=$(echo "$finaldest" |
-                               sed -En "s/(.+)\.(.+)/\1-copy$copy_n.\2/p")
-               [ "$finaldest" ] || finaldest="$dest/$fname-copy$copy_n"
+               finaldest="${realdest}/${body}-copy${copy_n}${ext}"
                if [ ! -e "$finaldest" ]; then
                    break
                elif [ ! "$copy_n" ]; then
@@ -176,33 +214,37 @@ main() {
            done
        fi
 
-       strace -q -ewrite $cmd $opts "$src" "$finaldest" 2>&1 |
+       strace -q -ewrite $cmd $opts -- "$src" "$finaldest" 2>&1 |
            awk "$H_FUN"'
         BEGIN { time_start = systime() }
         {
-            time_elapsed = systime() - time_start
             count += $NF
-            if (time_elapsed == 0 || count == 0) {
-                bytes_per_sec = -1
-                eta = -1
-            } else {
-                bytes_per_sec = count / time_elapsed
-                eta = (total_size - count) / bytes_per_sec
-            }
             if (total_size > 0 && count % 10 == 0) {
+                time_elapsed = systime() - time_start
+                if (time_elapsed == 0 || count == 0) {
+                    bytes_per_sec = -1
+                    eta = -1
+                } else {
+                    bytes_per_sec = count/time_elapsed
+                    eta = (total_size - count) / bytes_per_sec
+                }
                 percent = (count / total_size) * 100
                 printf "'$B'"substr(sprintf("%3d%% (%s/%s, %s/s, ETA: %s) %s to %s'$R'", percent, human(count), total_size_h, human(bytes_per_sec), human_time(eta), src, finaldest), 0, '$W')
             }
         }
-        END { print "'$B'Took " human_time(systime() - time_start) }' \
+        END { if (!no_timing) print "'$B'Took " human_time(systime() - time_start); }' \
                total_size=$total_size \
                total_size_h="$total_size_h" \
+               no_timing=$no_timing_opt \
                count=$count \
                src="$src" finaldest="$finaldest"
 
-       arg_size=$(du -sb "$src" 2>/dev/null | awk '{ print $1 }')
+       arg_size=$1
        count=$((count + arg_size))
+       shift
    done
+
+   [ $no_timing_opt -eq 1 ] && printf $B''
 
     if [ "$cmd" = mv ]; then
         echo 'Done moving'
@@ -215,19 +257,25 @@ main() {
 # to be used only for `lf` file manager. cp-p and mv-p must be on $PATH
 lf_paste() {
     id="$1"
-    send="while read -r line; do lf -remote \"send $id echo \$line\"; done && lf -remote 'send reload'"
-    load=$(cat ~/.local/share/lf/files)
-    mode=$(echo "$load" | sed -n '1p')
-    srcF=$(mktemp)
-    echo "$load" | sed '1d' > "$srcF"
-    s='' && [ ! -w . ] && s='sudo'
-    case "$mode" in
-        copy) cmd='cp-p';; move) cmd='mv-p';;
+    # permissions: auto (default), user, sudo
+    case "${2:-}" in
+        sudo) s='sudo' ;;
+        user) s='' ;;
+        *) s='' && [ ! -w . ] && s='sudo' ;;
     esac
-    cmd="$cmd --new-line"
-    [ "$mode" = copy ] && cmd="$cmd -a"
+    [ -e ~/.local/share/lf/files ] || exit 0
+    tmpdir=${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}
+    srcF=$(mktemp $tmpdir/lfpaste.XXXXXXXX)
+    sed '1d' ~/.local/share/lf/files > "$srcF"
+    mode=$(sed -n '1p' ~/.local/share/lf/files)
+    case "$mode" in
+        copy) cmd='cp-p --new-line --no-timing -a' ;;
+        move) cmd='cp-p --mv --new-line --no-timing' ;;
+        *) rm -f "$srcF"; exit 0 ;;
+    esac
+    send="(while read -r line; do lf -remote \"send $id echo \$line\"; last=\$line; done && lf -remote 'send reload' && lf -remote \"send $id echo \$last\")"
     sh -c "$s $cmd --backup=numbered -F \"$srcF\" . | $send && rm -f \"$srcF\" &"
-    rm ~/.local/share/lf/files
+    #rm ~/.local/share/lf/files
     lf -remote 'send clear'
 }
 
